title: The Prompt Commons
description: Free AI Configurators for Everyone
theme: jekyll-theme-cayman
# Add these new lines below for color customization
cayman:
  background_color: "#e9ecef"  # A light gray for the overall page background
  header_background_color: "#8B0000"  # A deep red for the header. Change to any color you like.
  header_text_color: "#ffffff"  # White text for the header to contrast the dark background
